version: "3.4"
services:
  reverse-proxy:
    image: mwaeckerlin/reverse-proxy
    ports:
      - 8080:8080
    build: .
    volumes:
      - type: bind
        source: ./reverse-proxy.conf
        target: /config/reverse-proxy.conf
    environment:
      DHPARAM: 128
      LETSENCRYPT: "off"

  localserver:
    image: mwaeckerlin/nginx

  demo:
    image: mwaeckerlin/nginx

  test:
    image: mwaeckerlin/nginx

  lokal:
    image: mwaeckerlin/nginx

  doesnotrun:
    image: mwaeckerlin/very-base
